-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 18:45:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tbl_arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_arquivo` (
  `arq_id` INT NOT NULL AUTO_INCREMENT,
  `arq_pasta` VARCHAR(80) NOT NULL,
  `arq_nome` VARCHAR(255) NOT NULL,
  `arq_data` DATE NOT NULL,
  `arq_extensao` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`arq_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_planos` (
  `plan_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NOT NULL,
  `plan_titulo` VARCHAR(80) NOT NULL,
  `plan_resumo` TEXT NOT NULL,
  `plan_descricao` LONGTEXT NOT NULL,
  `plan_valor` DOUBLE(4,2) NOT NULL,
  `plan_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  PRIMARY KEY (`plan_id`),
  CONSTRAINT `fk_tbl_planos_tbl_arquivo`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_professor` (
  `prof_id` INT NOT NULL AUTO_INCREMENT,
  `prof_nome` VARCHAR(60) NOT NULL,
  `prof_whatsapp` VARCHAR(15) NOT NULL,
  `prof_email` VARCHAR(80) NOT NULL,
  `prof_senha` VARCHAR(255) NOT NULL,
  `prof_descricao` TEXT NOT NULL,
  `prof_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  `prof_dtnascimento` DATE NOT NULL,
  `prof_endlogradouro` VARCHAR(80) NULL,
  `prof_endnumero` VARCHAR(30) NULL,
  `prof_endcomplemento` VARCHAR(30) NULL,
  `prof_endbairro` VARCHAR(50) NULL,
  `prof_endcidade` VARCHAR(80) NULL,
  `prof_enduf` VARCHAR(2) NULL,
  `prof_endcep` VARCHAR(10) NULL,
  `prof_urlstreaming` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`prof_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_aluno` (
  `alu_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  `alu_nome` VARCHAR(80) NOT NULL,
  `alu_cpf` VARCHAR(14) NOT NULL,
  `alu_senha` VARCHAR(255) NOT NULL,
  `alu_whatsapp` VARCHAR(15) NOT NULL,
  `alu_endlogradouro` VARCHAR(80) NOT NULL,
  `alu_endnumero` VARCHAR(30) NOT NULL,
  `alu_endcomplemento` VARCHAR(30) NULL,
  `alu_endbairro` VARCHAR(50) NOT NULL,
  `alu_endcidade` VARCHAR(80) NOT NULL,
  `alu_enduf` VARCHAR(2) NOT NULL,
  `alu_endcep` VARCHAR(10) NOT NULL,
  `alu_endpais` VARCHAR(50) NOT NULL,
  `alu_profissao` VARCHAR(50) NOT NULL,
  `alu_comoconheceu` VARCHAR(45) NULL,
  `alu_quemindicou` VARCHAR(45) NULL,
  `alu_dtvencimento` DATE NOT NULL,
  `alu_dthraulaexperimental` DATETIME NOT NULL,
  `alu_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  PRIMARY KEY (`alu_id`),
  CONSTRAINT `fk_tbl_aluno_tbl_professor1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `tbl_professor` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_tbl_planos1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `tbl_planos` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_alunoanamnese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_alunoanamnese` (
  `anam_id` INT NOT NULL AUTO_INCREMENT,
  `alu_id` INT NOT NULL,
  `anam_praticaatividade` SMALLINT(4) NOT NULL,
  `anam_qualatividade` VARCHAR(80) NULL,
  `anam_tomamedicamento` SMALLINT(4) NOT NULL,
  `anam_qualmedicamento` VARCHAR(80) NULL,
  `anam_fumante` SMALLINT(4) NOT NULL,
  `anam_fumaquantotempo` VARCHAR(80) NULL,
  `anam_hipertensao` SMALLINT(4) NOT NULL,
  `anam_doenca` SMALLINT(4) NOT NULL,
  `anam_qualdoenca` VARCHAR(80) NULL,
  `anam_apresentador` SMALLINT(4) NOT NULL,
  `anam_qualdor` VARCHAR(80) NULL,
  `anam_qualmovimentosentedor` VARCHAR(80) NULL,
  `anam_fezcirurgia` SMALLINT(4) NOT NULL,
  `anam_cirurgiaonde` VARCHAR(80) NULL,
  `anam_tempocirurgia` VARCHAR(80) NULL,
  `anam_objetivo` TEXT NOT NULL,
  PRIMARY KEY (`anam_id`),
  CONSTRAINT `fk_tbl_alunoanamnese_tbl_aluno1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `tbl_aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_alunohorarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_alunohorarios` (
  `ahor_id` INT NOT NULL AUTO_INCREMENT,
  `alu_id` INT NOT NULL,
  `ahor_diasemana` INT NOT NULL,
  `ahor_horario` TIME NOT NULL,
  PRIMARY KEY (`ahor_id`),
  CONSTRAINT `fk_tbl_alunohorarios_tbl_aluno1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `tbl_aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_aula` (
  `aula_id` INT NOT NULL AUTO_INCREMENT,
  `aula_dthrinicio` DATETIME NOT NULL,
  `aula_dthrtermino` DATETIME NULL,
  PRIMARY KEY (`aula_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_aulaaluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_aulaaluno` (
  `aalu_id` INT NOT NULL AUTO_INCREMENT,
  `aula_id` INT NOT NULL,
  `alu_id` INT NOT NULL,
  `aalu_dthrinicio` DATETIME NOT NULL,
  `aalu_dthrtermino` DATETIME NULL,
  PRIMARY KEY (`aalu_id`),
  CONSTRAINT `fk_tbl_aulaaluno_tbl_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `tbl_aula` (`aula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aulaaluno_tbl_aluno1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `tbl_aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_aulaprofessor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_aulaprofessor` (
  `aprof_id` INT NOT NULL AUTO_INCREMENT,
  `aula_id` INT NOT NULL,
  `prof_id` INT NOT NULL,
  `aprof_dthrinicio` DATETIME NOT NULL,
  `aprof_dthrtermino` DATETIME NULL,
  PRIMARY KEY (`aprof_id`),
  CONSTRAINT `fk_tbl_aulaprofessor_tbl_aula1`
    FOREIGN KEY (`aula_id`)
    REFERENCES `tbl_aula` (`aula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aulaprofessor_tbl_professor1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `tbl_professor` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_banner` (
  `ban_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NOT NULL,
  `ban_titulo` VARCHAR(50) NOT NULL,
  `ban_descricao` TEXT NULL,
  `ban_link` VARCHAR(255) NULL,
  `ban_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  PRIMARY KEY (`ban_id`),
  CONSTRAINT `fk_tbl_banner_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_parceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_parceiros` (
  `parc_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NOT NULL,
  `parc_nome` VARCHAR(50) NOT NULL,
  `parc_descricao` TEXT NOT NULL,
  `parc_link` VARCHAR(255) NULL,
  PRIMARY KEY (`parc_id`),
  CONSTRAINT `fk_tbl_parceiros_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_blog` (
  `blog_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NOT NULL,
  `parc_id` INT NULL,
  `blog_titulo` VARCHAR(100) NOT NULL,
  `blog_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  `blog_resumo` TEXT NOT NULL,
  `blog_texto` LONGTEXT NOT NULL,
  `blog_datahora` DATETIME NOT NULL,
  PRIMARY KEY (`blog_id`),
  CONSTRAINT `fk_tbl_blog_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_blog_tbl_parceiros1`
    FOREIGN KEY (`parc_id`)
    REFERENCES `tbl_parceiros` (`parc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_institucionalcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_institucionalcategoria` (
  `instc_id` INT NOT NULL AUTO_INCREMENT,
  `arq_id` INT NULL,
  `instc_titulo` VARCHAR(80) NOT NULL,
  `instc_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  `instc_relevancia` INT NULL,
  `instc_resumo` TEXT NULL,
  PRIMARY KEY (`instc_id`),
  CONSTRAINT `fk_tbl_institucionalcategoria_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_institucional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_institucional` (
  `inst_id` INT NOT NULL AUTO_INCREMENT,
  `instc_id` INT NOT NULL,
  `inst_titulo` VARCHAR(80) NOT NULL,
  `inst_ativo` SMALLINT(4) NOT NULL DEFAULT 1 COMMENT '0-N, 1-S',
  `inst_relevancia` INT NULL,
  `inst_texto` LONGTEXT NULL,
  PRIMARY KEY (`inst_id`),
  CONSTRAINT `fk_tbl_institucional_tbl_institucionalcategoria1`
    FOREIGN KEY (`instc_id`)
    REFERENCES `tbl_institucionalcategoria` (`instc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_newsletter` (
  `news_id` INT NOT NULL AUTO_INCREMENT,
  `news_nome` VARCHAR(80) NOT NULL,
  `news_whatsapp` VARCHAR(15) NOT NULL,
  `news_email` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`news_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_professorhorarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_professorhorarios` (
  `phor_id` INT NOT NULL AUTO_INCREMENT,
  `prof_id` INT NOT NULL,
  `phor_diasemana` INT NOT NULL,
  `phor_horario` TIME NOT NULL,
  PRIMARY KEY (`phor_id`),
  CONSTRAINT `fk_tbl_professorhorarios_tbl_professor1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `tbl_professor` (`prof_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_registroevolutivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_registroevolutivo` (
  `regev_id` INT NOT NULL AUTO_INCREMENT,
  `alu_id` INT NOT NULL,
  `arq_id` INT NULL,
  `regev_descricao` TEXT NOT NULL,
  `regev_datahora` DATETIME NOT NULL,
  PRIMARY KEY (`regev_id`),
  CONSTRAINT `fk_tbl_registroevolutivo_tbl_aluno1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `tbl_aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_registroevolutivo_tbl_arquivo1`
    FOREIGN KEY (`arq_id`)
    REFERENCES `tbl_arquivo` (`arq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tbl_transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbl_transacao` (
  `tsc_id` INT NOT NULL AUTO_INCREMENT,
  `alu_id` INT NOT NULL,
  `plan_id` INT NOT NULL,
  `tsc_datahora` DATETIME NOT NULL,
  `tsc_cartaofinal` VARCHAR(4) NOT NULL,
  `tsc_bandeira` INT NOT NULL,
  `tsc_valor` DOUBLE(11,2) NOT NULL,
  `tsc_dthrpagto` DATETIME NOT NULL,
  `tsc_dataprevrecimento` DATE NOT NULL,
  `tsc_recebido` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT '0-N, 1-S',
  `tsc_taxaadquirente` DOUBLE(4,2) NOT NULL,
  `tsc_valoradquirente` DOUBLE(4,2) NOT NULL,
  `tsc_valorrecebido` DOUBLE(11,2) NULL,
  `tsc_status` INT NOT NULL,
  `tsc_paymentid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tsc_id`),
  CONSTRAINT `fk_tbl_transacao_tbl_aluno1`
    FOREIGN KEY (`alu_id`)
    REFERENCES `tbl_aluno` (`alu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_transacao_tbl_planos1`
    FOREIGN KEY (`plan_id`)
    REFERENCES `tbl_planos` (`plan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
